### ISSUE TITLE
Test coverage for `MemoryAssert.assertGC`

### ISSUE THREAD

**Issue by jglick** [jenkinsci/jenkins-test-harness#360]
Does not look like this has any in-repo test coverage, which could be a problem if an `INSANE` update breaks usage: https://github.com/jenkinsci/jenkins-test-harness/pull/358#issuecomment-991173329

**Comment by timja** [comment]
`assertHeapUsage` is covered in https://github.com/jenkinsci/jenkins-test-harness/blob/master/src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java#L41

but not `assertGc`

**Comment by basil** [comment]
This is tracked in Jira as [JENKINS-67688](https://issues.jenkins.io/browse/JENKINS-67688).
