### ISSUE TITLE
Check compatibility of `RealJenkinsRule` with JaCoCo

### ISSUE THREAD

**Issue by jglick** [jenkinsci/jenkins-test-harness#366]
If you enable test coverage in your plugin, does `src/main/java/` exercised by `RealJenkinsRule` get counted? https://github.com/jenkinsci/jenkins-test-harness/blob/1cf3874a4b25456cb2d410210a2063af8fe06225/src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java#L279 means that the plugin under test will be loaded from `target/classes/` (via `target/test-classes/the.jpl`), which should be instrumented. However the instrumented code would be running in another JVM and so results may not be collected. Does JaCoCo support such a scenario?

**Comment by Vlatombe** [comment]
Jacoco supports on-the-fly instrumentation as well as offline instrumentation.
* In on-the-fly instrumentation a java agent needs to be added to each forked jvm command line (the jacoco maven plugin normally takes care of adding it to the surefire jvm)
* In offline instrumentation, you don't need a java agent, however you still need to provide some pieces of configuration (e.g. where should the coverage data should be dumped). These can be provided either by adding a configuration properties file to the classpath, or via a system property.

Then jacoco maven plugin provides a way to merge several coverage data files (https://www.eclemma.org/jacoco/trunk/doc/merge-mojo.html)
