### ISSUE TITLE
Regression: Jenkins test harness no longer compiles against recent cores

### ISSUE THREAD

**Issue by basil** [jenkinsci/jenkins-test-harness#370]
As of jenkinsci/jenkins#5320, the Jenkins test harness no longer compiles against recent cores: [`ExtractChangeLogParser#parse`](https://github.com/jenkinsci/jenkins-test-harness/blob/3b8b1441e939ed7e7406d168843cdac15edeb066/src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java#L66-L79)

Should be easy enough to fix in the usual way; see jenkinsci/subversion-plugin#259 and jenkinsci/jep#367.

CC @olamy @batmat

**Comment by basil** [comment]
@olamy @batmat Gentle ping.

**Comment by jglick** [comment]
Rather than https://github.com/olamy/jenkins-test-harness/commit/23a88cd172857ced3fd50ea8ca5e8ae4ca30c324 I would recommend removing use of Digester altogether, as in the links in the description.

**Comment by olamy** [comment]
this pattern has been used for most of the plugins during migration.
what is the added value? frankly it's adding extra work/extra lines of code to maintain, digester3 doesn't have security issues and `jenkins-test-harness` is a test library.
I don't want to be rude but if you prefer the other way feel free to do it.

**Comment by jglick** [comment]
> this pattern has been used for most of the plugins during migration.

Against my advice.

> what is the added value?

It is about avoiding adding something else to the dependencies of JTH.

I will see if I can find a few minutes to do it.
