### ISSUE TITLE
Upgrade HtmlUnit from 2.x.x to 3.x.x

### ISSUE THREAD

**Issue by basil** [jenkinsci/jenkins-test-harness#568]
### Problem

The Jenkins test harness depends on an outdated release of [HtmlUnit](https://www.htmlunit.org/) (at the time of this writing, 2.70.0).

### Solution

Upgrade HtmlUnit from its current version (at the time of this writing, 2.70.0) to the latest version (at the time of this writing, 3.0.0) in `jenkins-test-harness-htmlunit`, `jenkins-test-harness`, `plugin-pom`, Stapler, and Jenkins core.

### Implementation

Consult the [Migrating from HtmlUnit 2.x.x to HtmlUnit 3.x.x](https://www.htmlunit.org/migration.html) documentation:

1. Adjust the Maven group ID to `org.htmlunit`: 👉 https://github.com/jenkinsci/jenkins-test-harness-htmlunit/pull/110

    ```xml
    <dependency>
        <groupId>org.htmlunit</groupId>
        <artifactId>htmlunit</artifactId>
        <version>3.0.0</version>
    </dependency>
    ```

3. Change all package name references from `net.sourceforge.htmlunit` to `org.htmlunit`: 👉 https://github.com/jenkinsci/jenkins-test-harness/pull/589

    ```java
    import org.htmlunit.BrowserVersion;
    import org.htmlunit.WebClient;
    import org.htmlunit.html.HtmlInput;
    import org.htmlunit.html.HtmlPage;
    ```

5. Update input control value access by replacing all usages of `org.htmlunit.html.HtmlInput.getValueAttribute()` with `org.htmlunit.html.HtmlInput.getValue()` and replacing all usages of `org.htmlunit.html.HtmlInput.setValueAttribute(String)` with `org.htmlunit.html.HtmlInput.setValue(String)`.

### Success criteria

The success criteria for this ticket are as follows:

- `jenkins-test-harness-htmlunit` released with the latest version of HtmlUnit (at the time of this writing, 3.0.0) 👉 https://github.com/jenkinsci/jenkins-test-harness-htmlunit/pull/110
- `jenkins-test-harness` upgraded to the abovementioned release of `jenkins-test-harness-htmlunit` 👉 https://github.com/jenkinsci/jenkins-test-harness/pull/589
- `plugin-pom` upgraded to the abovementioned release of `jenkins-test-harness`
- Stapler upgraded to the abovementioned release of `jenkins-test-harness-htmlunit` 👉 https://github.com/jenkinsci/stapler/pull/464
- Jenkins core upgraded to the abovementioned release of `jenkins-test-harness` 👉 https://github.com/jenkinsci/jenkins/pull/8050
- Weekly release shipped with all of the above changes

**Comment by ggold7046** [comment]
Hi, I'm looking for some testing issues. Could anyone guide me how to find it ?

**Comment by MarkEWaite** [comment]
> Hi, I'm looking for some testing issues. Could anyone guide me how to find it ?

If you're interested in helping with this issue, then a careful reading of the instructions in this issue description will be enough to let you start contributing to help with this issue.

If you're looking for an issue to help that is different than this issue, then the Jenkins chat channels like https://app.gitter.im/#/room/#jenkinsci_newcomer-contributors:gitter.im are much more likely to offer ideas and suggestions.

**Comment by jglick** [comment]
@timja I suppose this can now be closed?

**Comment by timja** [comment]
I think so there’s still a long tail of plugins in https://docs.google.com/spreadsheets/d/1ih_gVd9uhxLw4BZ6IeJGrYsvu-DvIF0xovu4wZbaXy8/edit

But unsure if we need to keep this open

**Comment by basil** [comment]
I don't think we can declare victory until more of the orange and red rows in that spreadsheet turn green or yellow. There is still a large amount of work that remains to be completed.

**Comment by basil** [comment]
https://github.com/jenkinsci/next-build-number-plugin/pull/18 demonstrates the confusion that ensues when PRs are filed without context or a clean build.

**Comment by basil** [comment]
With the exception of Job Import, critical plugins with over 10,000 installations have been migrated.
