### ISSUE TITLE
WarExploder doesn't account for Gradle not always generating valid SHA1s in cache path

### ISSUE THREAD

**Issue by dgreene-r7** [jenkinsci/jenkins-test-harness#574]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

Try to run the test harness against `jenkins-war:2.332.3`.

### Expected Results

Test harness functions properly.

### Actual Results

`WarExploder` throws an `AssertionError` saying
> ~/.gradle/caches/modules-2/files-2.1/org.jenkins-ci.main/jenkins-war/2.332.3/48e994349a6ea9fff614dca79dd3c5f75c0f3d16/jenkins-war-2.332.3.war does not yet exist. Prime your development environment by running `mvn validate`.

This issue occurs because gradle's dependency caching trims leading zeros from the hash in the file cache. The SHA1 for jenkins-war 2.332.3 is `068b1e10fdddae7cad6f2b59c8c205d285321940` (see image)
![image](https://user-images.githubusercontent.com/15327249/235709178-ebf8f30b-84d9-4f19-ab37-993055a42ffd.png)

but the file is stored on disk in `~/.gradle/caches/modules-2/files-2.1/org.jenkins-ci.main/jenkins-war/2.332.3/68b1e10fdddae7cad6f2b59c8c205d285321940/jenkins-war-2.332.3.war`

This issue was raised with the gradle team in 2014 [here](https://discuss.gradle.org/t/sha-1-checksum-portion-of-file-path-in-gradle-cache-is-missing-leading-zeros/1244/2) with the response effectively being that it's an internal API with no guarantees.

I'd suggest implementing a conditional check to see if the directory hash is missing a character (stringified SHA1s are 40 characters and SHA256s are 64) that you prepend a `0` and test again.

**Comment by basil** [comment]
I would suggest that you file a pull request if you would like to see this issue fixed.
