### ISSUE TITLE
Automate updating of weekly release

### ISSUE THREAD

**Issue by basil** [jenkinsci/jenkins-test-harness#626]
Surely there must be a way to automate the likes of #625, #598, #555, #540, #502, #481, #473, #437 which I have been filing for over a year now.

**Comment by timja** [comment]
Both renovate and updatecli can do it.

e.g. https://docs.renovatebot.com/modules/manager/regex/#configuration-templates

roughly:

```
{
  "regexManagers": [
    {
      "fileMatch": ["^Jenkinsfile$"],
      "matchStrings": ["jenkins: '(?<currentValue>.*?)'"],
      "depNameTemplate": "org.jenkins-ci.main:jenkins-war",
      "datasourceTemplate": "maven"
    }
  ]
}
```

**Comment by timja** [comment]
Worked 👉 https://github.com/jenkinsci/jenkins-test-harness/pull/636
