### ISSUE TITLE
Make RealJenkinsRule IPv6 friendly

### ISSUE THREAD

**Issue by PereBueno** [jenkinsci/jenkins-test-harness#711]
`RealJenkinsRule` is defining listen address as `127.0.0.1` (https://github.com/jenkinsci/jenkins-test-harness/blob/master/src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java#L165).

This change should make it compatible with IPv6 so, if `java.net.preferIPv6Addresses=true` IPv6 address (`0:0:0:0:0:0:0:1`) will be used.

**Comment by MarkEWaite** [comment]
@PereBueno is this resolved by:

* #712
