### ISSUE TITLE
Unclear how to put RemainingActivityListener into "wait" mode

### ISSUE THREAD

**Issue by sparrowt** [jenkinsci/jenkins-test-harness#803]
### Describe your use-case which is not covered by existing documentation.

https://github.com/jenkinsci/jenkins-test-harness/issues/672 describes _false_ positives from `RemainingActivityListener` but I'm actually seeing a _true positive_ where it correctly identifies that a branch indexing job is still running, but simply logs a warning and carries on and then `TemporaryDirectoryAllocator.dispose` fails to delete the tmp directory due to that exact problem.

Stderr:
```
  51.632 [id=20]	WARNING	o.j.h.t.RemainingActivityListener#onTearDown: BranchIndexing[MyJobName] still seems to be running, which could break deletion of log files or metadata
  51.745 [id=20]	INFO	hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
  51.876 [id=20]	INFO	hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
  59.952 [id=20]	INFO	o.j.h.t.TemporaryDirectoryAllocator#dispose: deleting /tmp/j h2833791769982591998
  59.961 [id=203]	FINEST	hudson.XmlFile#write: Writing /tmp/j h2833791769982591998/jobs/MyJobName/indexing/indexing.xml
```
Resulting exception: (due to conflict between trying to delete a folder into which indexing.xml is being written)
```
java.io.IOException: /tmp/j h2833791769982591998/jobs/MyJobName
...
Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/j h2833791769982591998/jobs
```

I found [the option to "wait"](https://github.com/jenkinsci/jenkins-test-harness/blob/77428109fd1faf6d70ca8f3ecbf7eb196f970007/src/main/java/org/jvnet/hudson/test/RemainingActivityListener.java#L45-L48) instead of just logging a warning, which sounds like what I need - but how/where do I actually set something to make `RemainingActivityListener.wait` be true?

**Comment by sparrowt** [comment]
Ah, this clearly shows how much of a Java n00b I am - I finally discovered that the generically named `Boolean` is actually `java.lang.Boolean` and that https://docs.oracle.com/javase/8/docs/api/java/lang/Boolean.html#getBoolean-java.lang.String- is for getting system properties (despite having nothing to do with properties in its name).

So I guess the answer here is probably "you should have known" though the existance of this ticket perhaps shows that there are people like me who are trying to use Jenkins but are new to the Java world who would not find this obvious at all.

**Comment by timja** [comment]
Might want to waitUntilNoActivity after running your job or whatever is hanging around:
https://github.com/jenkinsci/promoted-builds-plugin/blob/cb0e96b41f63197120efe209026654e56a845de4/src/test/java/hudson/plugins/promoted_builds/conditions/DownstreamPassConditionTest.java#L64

**Comment by sparrowt** [comment]
Ah nice, is that equivalent, but a better more explicit way of doing it?

**Comment by timja** [comment]
Yes tests should cleanup after themselves, `RemainingActivityListener` is for catching mistakes in tests not something that should be used all the time

**Comment by sparrowt** [comment]
Thank you, appreciate your help - I guess the google-ability of this ticket is probably sufficient to provide help to anyone else struggling as I did so happy to close this now.
