### ISSUE TITLE
`org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite` fails with `503 Service Unavailable`

### ISSUE THREAD

**Issue by strangelookingnerd** [jenkinsci/jenkins-test-harness#830]
### Jenkins and plugins versions report

-

### What Operating System are you using (both controller, and any agents involved in the problem)?

-

### Reproduction steps

-

### Expected Results

-

### Actual Results

-

### Anything else?

I'm currently trying to prepare the migration for Jakarta EE for my plugins now that Jenkins `2.475` was released. 
The `InjectedTest` fail with `org.htmlunit.FailingHttpStatusCodeException: 503 Service Unavailable for http://localhost:49273/closures/?uuid=55ccee62-68fa-496d-9ea0-aa160113ca47`
See https://github.com/jenkinsci/custom-folder-icon-plugin/pull/381/checks?check_run_id=29724828510

Am I missing something?

**Comment by basil** [comment]
This is caused by an out-of-date test harness. See https://github.com/jenkinsci/plugin-pom?tab=readme-ov-file#running-the-entire-build-with-jetty-12-ee-8.
